### ISSUE TITLE
Copyright is not updated to 2022

### ISSUE THREAD

**Issue by melroy89** [memocash/frontend#7]
Copyright is still showing 2020.

Also your [other repo](https://github.com/memocash/memo) is deleted/private 😢 ..

**Comment by jchavannes** [comment]
This repo is deprecated.

https://github.com/memocash/index and https://github.com/memocash/desktop are the new repos.

**Comment by melroy89** [comment]
But both of those repos are not the website or are they?

**Comment by jchavannes** [comment]
Correct, the website is closed source

**Comment by melroy89** [comment]
Well the copyright is outdated on your website. That was my point.

**Comment by jchavannes** [comment]
@danger89 Oh I see. It is now updated. Thank you for reporting.
